runtime: nodejs20
service: kpi-payroll-service

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 5

env_variables:
  NODE_ENV: production
  PORT: "8080"
  DB_HOST: "/cloudsql/PROJECT_ID:asia-southeast2:erp-mysql"
  DB_PORT: "3306"
  DB_USER: root
  DB_PASSWORD: "24052026"
  DB_NAME: erp_kpi_payroll_db
  GCS_BUCKET_NAME: "GANTI_DENGAN_NAMA_BUCKET"
  AUTH_SERVICE_URL: "https://auth-employee-service-dot-PROJECT_ID.et.r.appspot.com"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX: "100"

beta_settings:
  cloud_sql_instances: "PROJECT_ID:project-akhir-144-161"

handlers:
  - url: /.*
    script: auto
    secure: always
