runtime: nodejs20
service: frontend-service

instance_class: F1

automatic_scaling:
  min_instances: 1
  max_instances: 3

env_variables:
  NODE_ENV: production
  # VITE_AUTH_SERVICE_URL: https://auth-employee-service-<hash>-uc.a.run.app
  # VITE_KPI_SERVICE_URL: https://kpi-payroll-service-<hash>-uc.a.run.app

build_env_variables:
  NODE_ENV: production

handlers:
  - url: /assets
    static_dir: dist/assets
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
